#!/bin/sh

# chkconfig: 2345 80 30
# description: Metasploit RPC and web daemons

### BEGIN INIT INFO
# Provides:          metasploit
# Required-Start:    $remote_fs $network $named
# Required-Stop:     $remote_fs $network $named
# Default-Start:     2 3 4 5
# Default-Stop:      0 1 6
# Short-Description: Metasploit RPC and web daemons
### END INIT INFO

exec /opt/metasploit/ctlscript.sh "$@"
